### ISSUE TITLE
No backtrace with Mingw64 and clang++

### ISSUE THREAD

**Issue by ArnaudValensi** [ianlancetaylor/libbacktrace#103]
When compiling with clang++ with mingw64, I don't have the right backtrace:
```
*** Segmentation Fault ***

0x561e4a67 ???
        ???:0
0x561edbc1 ???
        ???:0
0x9cf07ff7 ???
        ???:0
0x9e93241e ???
        ???:0
0x9e8e14a3 ???
        ???:0
0x9e930f4d ???
        ???:0
0x561e4a81 ???
        ???:0
```

However, it works with g++, but only with the `-no-pie` option, so I suspect that libbacktrace doesn't handle ASLR in this case.
Unfortunately clang seems to enable pie by default with no way to disable it.

I have the following with g++ and -no-pie:
```
*** Segmentation Fault ***

0x4000498a _Z15sigsegv_handleri
        src/test.cpp:58
0x4000da41 _gnu_exception_handler
        C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt_handler.c:213
0x9cf07ff7 ???
        ???:0
0x9e93241e ???
        ???:0
0x9e8e14a3 ???
        ???:0
0x9e930f4d ???
        ???:0
0x400049ad _Z12function_twov
        src/test.cpp:64
0x400049c4 _Z12function_onev
        src/test.cpp:68
0x40004a83 main
        src/test.cpp:87
0x400012ed __tmainCRTStartup
        C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:272
0x40001405 mainCRTStartup
        C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:193
0x9dc87613 ???
        ???:0
0x9e8e26a0 ???
        ???:0
0xffffffff ???
        ???:0
```
Is it normal that the symbols are not demangled?

Here my versions:

```
$ clang++.exe --version
clang version 15.0.5
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/mingw64/bin
```

```
$ g++.exe --version
g++.exe (Rev7, Built by MSYS2 project) 12.2.0
```

**Comment by ianlancetaylor** [comment]
I don't know how to implement this on Windows.  Happy to look at a patch, though.

**Comment by ArnaudValensi** [comment]
Is symbol resolution with ASLR already implemented for some platforms?

**Comment by ianlancetaylor** [comment]
Yes, on ELF.  It's the `base_address` values passed to `backtrace_dwarf_add`.

**Comment by Febbe** [comment]
Is this the format which must be implemented to show stacktraces on windows+mingw-w64? https://learn.microsoft.com/en-us/windows/win32/debug/pe-format

**Comment by ianlancetaylor** [comment]
Windows ASLR support has been committed, so this should work now.
