### ISSUE TITLE
Is it safe to load two executables?

### ISSUE THREAD

**Issue by diehard2** [ianlancetaylor/libbacktrace#116]
Hi, the interface _looks_ like it would support this, but I noticed that libbacktrace is doing a significant amount of caching and I couldn't quite figure out everything you're doing there. The use case is a symbol server.

if I do something like the following, is it safe with the cache strategy?

auto* exe_one = backtrace_create_state("./exe_one", 1, error_callback, nullptr);
auto* exe_two = backtrace_create_state("./exe_two", 1, error_callback, nullptr);

  for (auto program_counter : backtrace_one) {
                if (backtrace_pcinfo(exe_one , program_counter, detail::full_callback, , 0, 0) != 0) {
                    //Error
                }
            }

  for (auto program_counter : backtrace_two) {
                if (backtrace_pcinfo(exe_two , program_counter, detail::full_callback, 0, 0) != 0) {
                    //Error
                }
            }

**Comment by ianlancetaylor** [comment]
That should work fine, but the drawback is that there is no way to release all the cached information from the `backtrace_state` pointer.  So you wouldn't want to do it this for an unlimited number of different executables.
