### ISSUE TITLE
please add hints to error message "no debug info in Mach-O executable"

### ISSUE THREAD

**Issue by bhaible** [ianlancetaylor/libbacktrace#122]
The error message
```
libbacktrace: no debug info in Mach-O executable
```
gives no clue as to how to fix this issue.

Please change the message to
```
libbacktrace: no debug info in Mach-O executable. Make sure to use option '-g' and to invoke 'dsymutil'.
```

**Rationale:**
I used libbacktrace in a project with Automake, and it produced this error message. I then spent several hours:
- trying all possible debugging options of the clang compiler,
- trying a simple program - and in this simple program the stack traces worked.

**How to reproduce:**
[foo.c.gz](https://github.com/ianlancetaylor/libbacktrace/files/15378508/foo.c.gz)

It works in one step:
```
$ clang -g -O2 -I$HOME/include -L$HOME/lib foo.c -lbacktrace
$ ./a.out
Simple stack trace:
0x1002832e7
Full stack trace (requires debug info):
0x100283303 print_trace
        /Users/haible/foo.c:53
0x100283303 dummy_function
        /Users/haible/foo.c:60
0x100283303 main
        /Users/haible/foo.c:72
```

But it doesn't work in two steps, until a `dsymutil` invocation has been performed:
```
$ clang -g -O2 -I$HOME/include foo.c -c && clang -g -O2 -L$HOME/lib foo.o -lbacktrace
$ ./a.out
Simple stack trace:
0x102bf72e7
Full stack trace (requires debug info):
libbacktrace: no debug info in Mach-O executable
$ dsymutil a.out
$ ./a.out
Simple stack trace:
0x100e3b2e7
Full stack trace (requires debug info):
0x100e3b303 print_trace
        /Users/haible/foo.c:53
0x100e3b303 dummy_function
        /Users/haible/foo.c:60
0x100e3b303 main
        /Users/haible/foo.c:72
```

**References:**
- https://stackoverflow.com/questions/32297349/why-does-a-2-stage-command-line-build-with-clang-not-generate-a-dsym-directory
- https://stackoverflow.com/questions/10044697/where-how-does-apples-gcc-store-dwarf-inside-an-executable/12827463#12827463
- https://wiki.dwarfstd.org/Apple%27s_%22Lazy%22_DWARF_Scheme.md

If the error message had given me a hint to the missing `dsymutil` invocation, it would have saved me a **lot** of time.

**Comment by ianlancetaylor** [comment]
The intent is that you should not have to run dsymutil.  Something is wrong.  However, I don't have access to a MacOS system myself to debug this.

**Comment by bhaible** [comment]
> Something is wrong.

Maybe it's related to the test suite failures that I see on macOS 12? I've now reported them at https://github.com/ianlancetaylor/libbacktrace/issues/123 .

> The intent is that you should not have to run dsymutil.

Oh, you mean, libbacktrace is supposed to look at the file names stored in the executable (`nm -pa a.out | grep OSO`) and read the debugging information found in these files? This approach would only suffice in 1 out of 3 cases.

There are 3 cases:
- a) The executable is in the build tree, and the `.o` and `.a` files are still in the build tree, at their original locations.
- b) The executable is in the build tree, and the `.o` and `.a` files have been moved or deleted.
- c) The executable has been installed in a public location, and the build tree no longer exists.

In case a), `dsymutil` is not needed, if libbacktrace reads the debugging information from each of the .o files.

In case b) and c), `dsymutil` is needed. Therefore, for these cases, it is worth to improve the error message.

In case c) the user needs also to install the _executable_.dSYM directory; I hope they will understand this when they know about `dsymutil`.

**Comment by cooljeanius** [comment]
Related: [GCC bug 97082](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97082) and [GCC bug 105590](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105590)

**Comment by ianlancetaylor** [comment]
Thanks, I improved the error messages slightly.

**Comment by bhaible** [comment]
Thank you. I appreciate it.

**Comment by nickwilliams-zaxiom** [comment]
FWIW, I, too, needed to run `dsymutil`, and the discussion on this issue helped me figure that out. We compile hundreds of `.cpp` files with `clang++ -g` in one stage and then use `clang++` to link them, along with object files pulled in from other compilations, into either a shared library `.dylib` or executable binary. The data obtained from `libbacktrace` gave us the function name and library or executable path, but not the file path and line number. By running `dsymutil` on the shared library and executable, we now get file names and line numbers.

I do wonder if there's something we could be doing on the linking stage to obviate the need for running `dysmutil`. Or, conversely, something we're doing wrong that creates the need for running `dysmutil`. It would be nice to not need to do that, as with our current setup, we cannot distribute the output of `dysmutil` along with our shared libraries to our customers.
