### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by johnsonjh** [ianlancetaylor/libbacktrace#124]
The following (harmless, but useless) trailing whitespace was detected:
```
src/libbacktrace/dwarf.c:
        2042: Trailing whitespace
        2241: Trailing whitespace

src/libbacktrace/macho.c:
        677: Trailing whitespace
```

I noticed this integrating it into a project.  I disabled checking libbacktrace in my pre-commit hook, but fixing it is trivial.

PR in #125.

**Comment by ianlancetaylor** [comment]
Thanks.
