### ISSUE TITLE
Compilation error on MSVC 19.40

### ISSUE THREAD

**Issue by toge** [ianlancetaylor/libbacktrace#131]
I met compilation error on latest libbacktrace.
```
src\pecoff.c(86): error C2059: syntax error: '('
src\pecoff.c(89): error C2059: syntax error: '('
```

I think it is caused by [this commit](https://github.com/ianlancetaylor/libbacktrace/commit/11427f31a64b11583fec94b4c2a265c7dafb1ab3).

It works fine if deleting `CALLBACK` and `NTAPI`.

It also worked fine with source code from about 2021.
Is there any configuration needed to compile with MSVC?

**Comment by ianlancetaylor** [comment]
Is this on x86 or ARM?

**Comment by toge** [comment]
@ianlancetaylor 
Sorry for lack of information.
It is on x86_&4.

**Comment by ianlancetaylor** [comment]
Should be fixed now, I think.  Thanks.
