### ISSUE TITLE
llvm scan-build NULL ptr in  lookup_abbrev() passed to bsearch()

### ISSUE THREAD

**Issue by aakefbs** [ianlancetaylor/libbacktrace#15]
After updating the scan-build checks for our project, which uses libbacktrace, the anaylzer reports that bsearch() gets an invalid NULL ptr. I can't upload the html file here, so please fine it here

http://www.aakef.fastmail.fm/linux/libbacktrace_dwarf.c.html

For now I have added this patch to our code, as I don't have time to investigate more in details.

```diff --git a/libbacktrace/dwarf.c b/libbacktrace/dwarf.c
index 55b8d7dc2a..ec8d3bec6a 100644
--- a/libbacktrace/dwarf.c
+++ b/libbacktrace/dwarf.c
@@ -1167,6 +1167,13 @@ lookup_abbrev (struct abbrevs *abbrevs, uint64_t code,
   /* Otherwise we have to search.  */
   memset (&key, 0, sizeof key);
   key.code = code;
+
+  if (!abbrevs->abbrevs)
+  { /* Fixes scan-build warning */
+      error_callback (data, "NULL ptr abbrevs", 0);
+      return NULL;
+  }
+
   p = bsearch (&key, abbrevs->abbrevs, abbrevs->num_abbrevs,
               sizeof (struct abbrev), abbrev_compare);
   if (p == NULL)
```

**Comment by ianlancetaylor** [comment]
If I understand you correctly, you are saying that an analyzer has suggested that there is some case in which the code passes a `NULL` pointer to `bsearch`.  As far as I can see that is just a deficiency in the analyzer.  I don't see any way that it could actually happen.  In particular note that `read_abbrevs` will cause an earlier failure if there are no abbrev entries.  I don't mind too much adding an annotation here or there to help an analyzer, but I'm not inclined to add real code.

Thanks for reporting this, but I'm going to close the issue.  Please comment if you disagree or if I've misunderstood.
