### ISSUE TITLE
Windows: No such file or directory when running app instead of app.exe

### ISSUE THREAD

**Issue by tehKaiN** [ianlancetaylor/libbacktrace#18]
If I type in cmd `app` then backtrace doesn't work since there is no `app` file. If I run `app.exe` everything works fine. Is this a bug or feature?

There could be a windows-only code which would check if passed filename is without extension, and if so it would try attaching ".exe".

Also, I'm willing to implement it :)

**Comment by ianlancetaylor** [comment]
Yes, on Windows the code should certainly try appending ".exe" to argv[0].
