### ISSUE TITLE
backtrace deadlocks when jemalloc heap profiling is enabled

### ISSUE THREAD

**Issue by jsgf** [ianlancetaylor/libbacktrace#20]
Basically the same bug as https://github.com/libunwind/libunwind/issues/16 -

> The implementation of `dl_iterate_phdr` in glibc both takes locks, and allocates memory. People hit this sporadically in production.
> Barring a fix in glibc, the best fix is probably an optionally linked library that will override dlopen, dlclose, and dl_iterate_phdr with a lock-free and non-mallocing cache.

As a hacky workaround I think we can disable jemalloc's heap profiling with `mallctl` while calling `dl_iterate_phdr` within libbacktrace, but that would still leave problems for other malloc or heap profiling implementations.

**Comment by ianlancetaylor** [comment]
I don't think there is any reliable workaround we can provide for this class of problems.  Instead I added a paragraph to the README explaining that for uses within a signal handler or a memory profiler programs need to make an initial call to a libbacktrace function before trying to use it in those cases.  The initial call will make the `dl_iterate_phdr` call.
