### ISSUE TITLE
Use of uninitialised value in libbacktrace/pecoff.c

### ISSUE THREAD

**Issue by ranma42** [ianlancetaylor/libbacktrace#3]
In `coff_add()`, `str_size` is declared as a `size_t`, but if there is a symbol table, only 4 bytes of it are initialised:

```C
memcpy (&str_size, syms_view.data + syms_size, 4);
```

`str_size` should probably be declared as a `uint32_t`.

The bug at https://github.com/rust-lang/rust/issues/28447 was caused by this.
It was fixed in the Rust local copy of libbacktrace: https://github.com/rust-lang/rust/commit/55e2b7e1b4606ae0bc684293f011b7006d1f1258

This was reported at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69314

**Comment by dscho** [comment]
Is this not addressed by https://github.com/ianlancetaylor/libbacktrace/pull/6? That Pull Request sits unanswered for months already, and it looks pretty good from my side, so I have no idea why you don't just click "Merge" @ianlancetaylor...
