### ISSUE TITLE
Set license also in github metadata

### ISSUE THREAD

**Issue by ifradeo** [ianlancetaylor/libbacktrace#31]
The project description makes it clear that is BSD and the LICENSE file is in place, but github metadata still reports the license of the project as "other". I think that needs to be set manually.

**Comment by ianlancetaylor** [comment]
How do I do that?

**Comment by ifradeo** [comment]
Actually I cannot find where to change it... :/ 

This is the closest I can find: let github create the LICENSE file for you:
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by ianlancetaylor** [comment]
I can't realistically change the license, since the code is just copied out of the GCC repository.  So I guess this will remain unfixed for now.  Sorry.
