### ISSUE TITLE
read.c fails to handle views of more than 2,147,479,552 bytes

### ISSUE THREAD

**Issue by Aaron1011** [ianlancetaylor/libbacktrace#32]
[On Linux](http://man7.org/linux/man-pages/man2/read.2.html#NOTES), the `read` syscall will transfer at most 2,147,479,552 bytes (~2.147 GB). This means that `read` will return `2,147,479,552` even if the file being read from has more data available.

`read.c` interprets this condition as the file being too short, resulting in an error:

https://github.com/ianlancetaylor/libbacktrace/blob/559ab7cab4a6002124863d493bd09a376a690e76/read.c#L81-L86

If a file's debuginfo sections add up to more than 2,147,479,552 bytes, this will cause a spurious failure:

https://github.com/ianlancetaylor/libbacktrace/blob/559ab7cab4a6002124863d493bd09a376a690e76/elf.c#L3162-L3165

I recognize that it's unusual for a file to have such a large amount of debug info. However, it would be very useful if libbacktrace could handle this case by using multiple `read` calls, as this issue makes it impossible to generate backtraces for such files.

**Comment by ianlancetaylor** [comment]
While I'm fine with fixing this, I need to check: is this a problem that actually occurs, or is this purely theoretical?  The file read.c should never be used on a GNU/Linux system.

**Comment by Aaron1011** [comment]
@ianlancetaylor: This actually occured - see https://github.com/rust-lang/rust/issues/69151.

**Comment by ianlancetaylor** [comment]
Again, though, read.c should never be used on a GNU/Linux system.  Are you sure you've diagnosed the problem correctly?

**Comment by Aaron1011** [comment]
@ianlancetaylor: Yes - I stepped through with `gdb`, and verified that `read.c` was being used.

It looks like [`read.c` is being explicitly selected by `backtrace-rs`](https://github.com/rust-lang/backtrace-rs/blob/190b2f9bb1df384be686eadd1d14cb95de0d87d4/crates/backtrace-sys/build.rs#L33), which is used by the Rust compiler.

Is `read.rs` unsupported on GNU/linux systems, or is it just that `mmapio.c` is more efficient?

**Comment by ianlancetaylor** [comment]
I see.  Thanks for the info.  Yes, mmapio.c is more efficient.  I see they are also using alloc.c rather than mmap.c, which means that that version won't work correctly if invoked from a signal handler.  Odd.

**Comment by MeFisto94** [comment]
Well, this triggers #29.
I am just about to check the patch, but that's why my debugger stepped into read.c as well!

**Comment by ianlancetaylor** [comment]
@Aaron1011 Could you show the `readelf -S --wide` output of the failing binary?  I'm wondering whether there is really 2G of debug data in this file or whether, as @MeFisto94 suggests, this is due to data that we don't really need to read.  Thanks.
