### ISSUE TITLE
Remove generated files from git

### ISSUE THREAD

**Issue by rossburton** [ianlancetaylor/libbacktrace#33]
The git repository contains many files that are generated and shouldn't be stored in git.

`configure`, `aclocal.m4`, all of `config/`, and so on.

**Comment by ianlancetaylor** [comment]
The contents of the `config` directory are not generated.

In any case, this is intentional.  It makes it possible to build the library without having to first install autoconf, automake and libtool.  It also means that people who don't want to adjust the configury get a tested build.
