### ISSUE TITLE
no symbol, filename, lineno on macOS 10.15

### ISSUE THREAD

**Issue by changloong** [ianlancetaylor/libbacktrace#37]
I try use  libbacktrace  on my project.  for linux it work very well, but macOS can not find symbol. 

I build  with clang option `-gdwarf-4`,  I can confirm the object file include dwarf debug data by run `dwarfdump test.o`

but the final binary has no such section anymore:
```sh
dwarfdump ./test
.debug_info contents:
```
backtrace_full_callback get `NULL` for `filename`, `lineno`, `fn`. 

`atos` is able to get the symbol and line number.

What to do to make it return filename and lineno ?   Is there some option I can pass to `ld` to generate linux like bianry with `.debug_info` section ?

**Comment by changloong** [comment]
I link the binary with `-no_pie` to avoid the base address.  

I add debug code into  `macho.c` function `macho_syminfo` to print all  name and address:
```c
	  printf("\nmacho_add_symtab:%d ndefs=%llu\n", __LINE__, ndefs);
	  for(size_t i=0; i< ndefs; i++){
		  printf("\taddr=%p, %s\n", macho_symbols[i].address, macho_symbols[i].name);
	  }
	  printf("\n");
```

the output:
```sh
	addr=0x100024030, main
```

the test source code:
```c
    printf("main=%p\n", &main);
    backtrace_pcinfo(state, (uintptr_t)&main, on_backtrace_pc, on_backtrace_error, NULL);
```

Use `atos -o ./test 0x100024030`,   print the correct symbol name with filename and lineno. but on_backtrace_pc print NULL.

**Comment by changloong** [comment]
@ianlancetaylor care to comment on this ?

**Comment by changloong** [comment]
I generate `.dSYM` myself and provide the file path to `backtrace_create_state`, still get the null function name and null source name, 0 lineno.

`atos` and `lldb` is able to get the function and source lineno.

**Comment by ianlancetaylor** [comment]
Can you give me an exact set of steps that reproduces the problem?  Also mention which version of clang you are using.  Thanks.

**Comment by changloong** [comment]
my clang version  is 11.0.3 (clang-1103.0.32.29). 

```c
#include "stdio.h"
int main() {
	printf("main=%p\n", main);
        return 0;
}
```

build with: ` clang -Xlinker -no_pie -g -gdwarf-4 test_errors.c -v`

try atos
```sh
atos -o ./a.out 0x100000f50
main (in a.out) (test_errors.c:6)
```




[a.tar.gz](https://github.com/ianlancetaylor/libbacktrace/files/4436323/a.tar.gz)

**Comment by ianlancetaylor** [comment]
Thanks, but I don't understand the test case: it doesn't call libbacktrace.  libbacktrace is for a program to get backtraces of itself while it is running; a test case that doesn't call libbacktrace doesn't show anything.

**Comment by changloong** [comment]
I open the `dSYM` file from other process to do the debug work, to avoid link libbacktrace into the product binary.

I am use libbacktrace with d language with extern(C):  https://github.com/ldc-developers/ldc/releases/download/v1.21.0-beta1/ldc2-1.21.0-beta1-osx-x86_64.tar.xz 

the test case: 

```d
import core.stdc.stdio;
import core.stdc.stdint;
extern(C)  @nogc nothrow :
struct backtrace_data;
struct backtrace_state;
alias backtrace_error_callback  = extern(C) void function(backtrace_data* data, const(char)* msg, int errnum);
alias backtrace_full_callback   = extern(C) int function(backtrace_data* data, uintptr_t pc, const(char)* filename, int lineno, const(char)* fn);
alias backtrace_simple_callback = extern(C) int function(backtrace_data* data, uintptr_t pc);
alias backtrace_syminfo_callback = extern(C) void function(backtrace_data* data, uintptr_t pc, const(char)* symname, uintptr_t symval, uintptr_t symsize);

backtrace_state* backtrace_create_state (const(char)* filename, int threaded, backtrace_error_callback error_callback, backtrace_data* data);
int backtrace_full(backtrace_state *state, int skip, backtrace_full_callback callback, backtrace_error_callback error_callback, backtrace_data* data);
int backtrace_simple(backtrace_state *state, int skip, backtrace_simple_callback callback,  backtrace_error_callback error_callback, backtrace_data* data);
void backtrace_print(backtrace_state *state, int skip, FILE*);
int backtrace_pcinfo(backtrace_state *state, uintptr_t pc, backtrace_full_callback callback, backtrace_error_callback error_callback, backtrace_data* data);
int backtrace_syminfo(backtrace_state *state, uintptr_t addr, backtrace_syminfo_callback callback, backtrace_error_callback error_callback, backtrace_data* data);

void on_backtrace_error(void* p, const char* msg, int errnum){
	printf("on_backtrace_error:%s errnum:%d\n",msg, errnum);
}

int on_backtrace_pc(void* d, uintptr_t pc, const char* filename, int lineno, const char* fn){
	printf("on_backtrace_pc: pc:%p, %s from %s:%d\n", pc, fn, filename, lineno);
	return 0;
}

int main(){
	printf("main=%p\n", &main);
        backtrace_state* gState;
        gState  = backtrace_create_state("/d/test_errors.dSYM/Contents/Resources/DWARF/test_errors", 0, &on_backtrace_error, null);
	if( gState) backtrace_pcinfo(gState, cast(uintptr_t) &main, &on_backtrace_pc, &on_backtrace_error, null);
        return 0;
}
```

to build the code:
```sh
ldmd2 -betterC test_errors.d -L-no_pie -g -L-lbacktrace --dwarf-version=2 -v
dsymutil test_errors
./test_errors
main=0x100000cf0
on_backtrace_pc: pc:0x100000cf0, (null) from (null):0
```
I test dwarf-version 2, 3, 4.  all get same results.

test with `atos`, I can get the filename and lineno.
```sh
atos -o ./test_errors 0x100000cf0
main (in test_errors) (test_errors.d:31)
```
use lldb with `image lookup -a` also able to find the filename and lineno.

**Comment by ianlancetaylor** [comment]
That is an interesting thing to try, but it's not supported.  libbacktrace is designed to be linked into a program in order to get backtraces of that program while it is running.  It's not for getting information about a different program.  If it works, great.  If it fails, sorry.  It's not something that I'm going to work on.

My first guess for why it isn't working for you is that you are generating position independent code and libbacktrace doesn't have the correct load address for the target executable.  That's just a guess, though.

**Comment by changloong** [comment]
hi @ianlancetaylor 
The first example is about the open dSYM file from other process, the last example is use libbacktrace  linked into a program.

the example generate binary with `-no_pie` to generating position independent code, and I can use `atos` or `lldb` get correct filename and lineno.   libbacktrace is working for linux binary but not osx binary.  

This attachment is the binary file I build from OSX 10.15.
[test_errors.tar.gz](https://github.com/ianlancetaylor/libbacktrace/files/4460399/test_errors.tar.gz)

**Comment by ianlancetaylor** [comment]
Thanks, but I'm not willing to run or investigate a binary.

You shouldn't be passing the name of the dSYM file to `backtrace_create_state`.  In the normal case you should just pass `NULL`.  Then find out whether libbacktrace is able to find the dSYM file.  Then find out why it can't map PC values to the data it finds there.

Since you are using the D compiler it may have something to do with the DWARF information generated by D.  I don't know.

**Comment by changloong** [comment]
pass `null` as path:
```sh
main=0x100000d30
on_backtrace_error:libbacktrace could not find executable to open errnum:0
```
pass absolute path or the `dSYM`:
```sh
main=0x100000d10
on_backtrace_pc: pc:4294970640, (null) from (null):0
```

As you can see from https://github.com/ianlancetaylor/libbacktrace/issues/37#issuecomment-600065961 ,  libbacktrace is able to load the symbols name, but not able to  find it with `backtrace_pcinfo` or `backtrace_full`.  and `atos` or `lldb` is able to get it.

`ldc2` and `clang` both use `libllvm`  to generate binary, I agree there must be some diff between them.
