### ISSUE TITLE
std::exception

### ISSUE THREAD

**Issue by ambitslix** [ianlancetaylor/libbacktrace#39]
Hello,

I'm already using the library for custom C++ exception but I'd like to add backtrace capability for STL exceptions. I found an approach that might work but I'm not sure how to integrate it with libbacktrace. The idea is to replace __cxa_throw like so:

```
  void __cxa_throw(void* ex, void* info, void (*dest)(void*))
  {
    //demangle and store backtrace here
    .. demangle(reinterpret_cast<const std::type_info*>(info)->name());
    ...backtrace(...);

    static void (*const rethrow)(void*, void*, void (*)(void*)) __attribute__((noreturn)) = (void (*)(void*, void*, void (*)(void*)))dlsym(RTLD_NEXT, "__cxa_throw");
    rethrow(ex, info, dest);
  }
``` 

This works by itself but I'd like to tie it with library. Should I just call backtrace_full from within the new throw handler? Are there any caveats? Perhaps there is  a better way?

Thanks!

**Comment by ianlancetaylor** [comment]
Do you want to do this for all exceptions, or just exceptions that are not caught?  Because it doesn't make sense to me to do this for all exceptions.

For exceptions that are not caught, can you use `std::set_unexpected`?

Other than that, I don't know the answer to your question.  I haven't tried to keep up with C++ changes in recent years.

**Comment by ambitslix** [comment]
The issue is that for custom exceptions we can get a trace because we can capture the trace before the exception is thrown. For std::exception and friends though all you get is whatever is left at the catch block. So ideally you want to see a backtrace for all exceptions, and that method works. I apologize if this is the wrong place to ask but I'm using this library successfully and ended up doing what I outlined and it works pretty nicely, but I was wondering if you have any thought on it...

**Comment by ianlancetaylor** [comment]
I don't, and honestly I'm the wrong person to ask.
