### ISSUE TITLE
Possibly incorrect binary search usage in dwarf.c

### ISSUE THREAD

**Issue by dfyz** [ianlancetaylor/libbacktrace#44]
I'm using `backtrace_pcinfo()` for printing backtraces, and I think I'm hitting an edge case in `libbacktrace` for some PC values where lldb/gdb work just fine. Unfortunately it's hard to make a small self-contained example out of the binary I have (and I can't attach the binary itself since it's proprietary software) but hopefully the following should be enough to investigate the problem.

For my binary, the problematic PC is `0x24a4265`. When `libbacktrace` tries to find the relevant DWARF unit, `dwarf_lookup_pc()` bails out early at [this line](https://github.com/ianlancetaylor/libbacktrace/blob/master/dwarf.c#L3916) because the `bsearch()` call from the line above, which uses `unit_addrs_search()` as a comparison function, returns `NULL`. I printed out all unit addresses I have along with what the comparison function outputs for them, and here's the relevant part:
```text
[...]
Addr #22782: low = 0x24a3f40, high = 0x24a3f72, unit_addrs_search(pc, addr) = 1, filename = [REDACTED]/1204c9a5db0a366fa0204390af.cpp
Addr #22783: low = 0x24a3f80, high = 0x24a4024, unit_addrs_search(pc, addr) = 1, filename = [REDACTED]/4f8020ed77d34d3bbd744e8cea.cpp
Addr #22784: low = 0x24a4030, high = 0x24a403f, unit_addrs_search(pc, addr) = 1, filename = [REDACTED]/__tests__.exception.reg3.cpp
Addr #22785: low = 0x24a4040, high = 0x24a4166, unit_addrs_search(pc, addr) = 1, filename = [REDACTED]/__vcs_version__.c
Addr #22786: low = 0x24a4170, high = 0x24a4458, unit_addrs_search(pc, addr) = 0, filename = [REDACTED]/exception.pyx.cpp
Addr #22787: low = 0x24a4170, high = 0x24a4170, unit_addrs_search(pc, addr) = 1, filename = [REDACTED]/_1204c9a5db0a366fa0204390af.yasm
Addr #22788: low = 0x24a4170, high = 0x24a4170, unit_addrs_search(pc, addr) = 1, filename = [REDACTED]/_4f8020ed77d34d3bbd744e8cea.yasm
Addr #22789: low = 0x24a4460, high = 0x24a4cea, unit_addrs_search(pc, addr) = -1, filename = [REDACTED]/exception.pyx.cpp
Addr #22790: low = 0x24a4cf0, high = 0x24a66b6, unit_addrs_search(pc, addr) = -1, filename = [REDACTED]/exception.pyx.cpp
Addr #22791: low = 0x24a66c0, high = 0x24a6739, unit_addrs_search(pc, addr) = -1, filename = [REDACTED]/exception.pyx.cpp
[...]
```

Notice that there are three address ranges matching my PC (`#22786`, `#22787`, `#22788`), and the comparison function outputs `0` for the first one and `1` for the remaining ones (because nested addresses are sorted with `unit_addrs_compare()`, which makes the smallest range come last).

This seems to contradict the contract for `bsearch()`:
> The array shall consist of: all the elements that compare less than, all the elements that compare equal to, and all the elements that compare greater than the key object, in that order.

I can't say for certain because I didn't read the source for `bsearch()` in glibc, but I think this disrepancy is what makes `bsearch()` fail even though there are valid address ranges covering the PC. I also didn't read the DWARF standard in its entirety, so I can't say if this DWARF information with overlapping ranges is valid, but it looks legitimate to me (and, again, gdb/lldb correctly find the corresponding line/column/file for this PC).

**Comment by georgthegreat** [comment]
@ianlancetaylor, could you, please, take a look?

**Comment by georgthegreat** [comment]
The issue was fixed according to our CI system.

The fix was uploaded into gcc monorepo, which was not synced here.
Can such sync be automated or should we switch to gcc monorepo instead?

**Comment by ianlancetaylor** [comment]
It will be synced here but I haven't had time.  Probably this week, I hope.

**Comment by georgthegreat** [comment]
Thanks!

**Comment by ianlancetaylor** [comment]
This should now be fixed in the github sources.  Thanks for reporting it and for analyzing the bug.
