### ISSUE TITLE
Supplying dependency for missing dlfcn.h, on Windows 10: review of dlfcn-win32, as a candidate, for a dependency (or a merger)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [ianlancetaylor/libbacktrace#46]
Hello again.

So, I was checking all missing headers, while compiling [https://go.googlesource.com/gollvm](https://go.googlesource.com/gollvm/) and [https://github.com/ianlancetaylor/libbacktrace](https://github.com/ianlancetaylor/libbacktrace) .

So while I was checking

> -- Looking for dlfcn.h
> -- Looking for dlfcn.h - not found
> 

I found that such a project exists:
[https://github.com/dlfcn-win32/dlfcn-win32](https://github.com/dlfcn-win32/dlfcn-win32)
. It seems to be oriented against CMake - so it could be vibrant with [https://github.com/ianlancetaylor/libbacktrace/issues/12](https://github.com/ianlancetaylor/libbacktrace/issues/12).

@TimothyGu , @pali , @ramiropolla , @traversaro - please follow up.
Also hence [https://github.com/ianlancetaylor/libbacktrace/issues/12](https://github.com/ianlancetaylor/libbacktrace/issues/12)

Ivan

**Comment by ianlancetaylor** [comment]
There is no reason to use <dlfcn.h> on Windows.  It's fine that the file does not exist there.
