### ISSUE TITLE
macho_add_fat() has wrong offset calculation

### ISSUE THREAD

**Issue by fxcoudert** [ianlancetaylor/libbacktrace#52]
I first reported this at GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96973

The issue is in macho_add_fat() in calculating the offset for a given arch. If !is_64, then the offset is retrieved as a `uint32_t`, and currently it is cast into a `uint64_t` before calling `bswap64` (if `swapped` is true, which is the case here). That's wrong, and it should be `bswap32` that is called, before casting to a wider type.

The patch below fixes it:

```
diff --git a/libbacktrace/macho.c b/libbacktrace/macho.c
index bd737226ca6..5974d8d8a5b 100644
--- a/libbacktrace/macho.c
+++ b/libbacktrace/macho.c
@@ -797,9 +797,13 @@ macho_add_fat (struct backtrace_state *state, const char *filename,
       uint32_t fcputype;
 
       if (is_64)
-	memcpy (&fat_arch,
-		(const char *) arch_view.data + i * arch_size,
-		arch_size);
+	{
+	  memcpy (&fat_arch,
+		  (const char *) arch_view.data + i * arch_size,
+		  arch_size);
+	  if (swapped)
+	    fat_arch.offset = __builtin_bswap64 (fat_arch.offset);
+	}
       else
 	{
 	  struct macho_fat_arch fat_arch_32;
@@ -809,7 +813,10 @@ macho_add_fat (struct backtrace_state *state, const char *filename,
 		  arch_size);
 	  fat_arch.cputype = fat_arch_32.cputype;
 	  fat_arch.cpusubtype = fat_arch_32.cpusubtype;
-	  fat_arch.offset = (uint64_t) fat_arch_32.offset;
+	  if (swapped)
+	    fat_arch.offset = (uint64_t) __builtin_bswap32(fat_arch_32.offset);
+	  else
+	    fat_arch.offset = (uint64_t) fat_arch_32.offset;
 	  fat_arch.size = (uint64_t) fat_arch_32.size;
 	  fat_arch.align = fat_arch_32.align;
 	  fat_arch.reserved = 0;
@@ -821,14 +828,9 @@ macho_add_fat (struct backtrace_state *state, const char *filename,
 
       if (fcputype == cputype)
 	{
-	  uint64_t foffset;
-
 	  /* FIXME: What about cpusubtype?  */
-	  foffset = fat_arch.offset;
-	  if (swapped)
-	    foffset = __builtin_bswap64 (foffset);
 	  backtrace_release_view (state, &arch_view, error_callback, data);
-	  return macho_add (state, filename, descriptor, foffset, match_uuid,
+	  return macho_add (state, filename, descriptor, fat_arch.offset, match_uuid,
 			    base_address, skip_symtab, error_callback, data,
 			    fileline_fn, found_sym);
 	}
```

Without the patch, `macho_add_fat` fails when called on macOS 10.15 system libraries. With the patch, everything works fine!

**Comment by ianlancetaylor** [comment]
Thanks.  There's no need to report libbacktrace issues both here and at gcc.gnu.org/bugzilla, I consider the GCC sources to be the master copy anyhow.

**Comment by fxcoudert** [comment]
@ianlancetaylor ok, I wasn't sure which way you'd prefer

**Comment by fxcoudert** [comment]
In any case, please consider committing to GCC the straightforward fix in https://github.com/ianlancetaylor/libbacktrace/pull/40 (either the original PR, or my slightly modified version). It does fix an issue that is triggered during gfortran backtraces on both x86_64-apple-darwin and aarch64-apple-darwin.

**Comment by ianlancetaylor** [comment]
This is now fixed in the GitHub sources.
