### ISSUE TITLE
make[1]: don't know how to make elf_32.lo

### ISSUE THREAD

**Issue by advancedwebdeveloper** [ianlancetaylor/libbacktrace#57]
>  $ make check
> make  libbacktrace_alloc.la  libbacktrace_noformat.la   libbacktrace_instrumented_alloc.la allocfail    test_elf_32 test_elf_64  test_macho test_xcoff_32  test_xcoff_64 test_pecoff  test_unknown unittest  unittest_alloc btest btest_lto btest_alloc stest  stest_alloc  ztest  ztest_alloc edtest edtest_alloc ttest  ttest_alloc   dwarf5  dwarf5_alloc mtest  xztest xztest_alloc
> `libbacktrace_alloc.la' is up to date.
> `libbacktrace_noformat.la' is up to date.
> `libbacktrace_instrumented_alloc.la' is up to date.
> `allocfail' is up to date.
> make[1]: don't know how to make elf_32.lo. Stop
> 
> make[1]: stopped in /usr/home/oceanfish81/libbacktrace

> $ uname -a
> FreeBSD gollvm.build.server 13.0-CURRENT FreeBSD 13.0-CURRENT #0 b9403d7aae8-c254071(main): Thu Oct 29 08:06:03 UTC 2020     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

> https://www.freshports.org/devel/libepoll-shim was installed.

As for the main source code base - end-user API was compiled without errors.

**Comment by advancedwebdeveloper** [comment]
>  $ make check-TESTS
> PASS: allocfail.sh
> make[1]: don't know how to make mtest_minidebug. Stop
>

**Comment by ianlancetaylor** [comment]
What version of `make` are you using?

**Comment by advancedwebdeveloper** [comment]
gmake-4.3_2

**Comment by ianlancetaylor** [comment]
At the moment I don't see how that is possible.  What is the output of `make --version`?  How exactly did you build libbacktrace?

**Comment by advancedwebdeveloper** [comment]
$make --version

does not offer any output. I have installed "make" via "pkg" tool - so that could be checked from FreeBSD's (13.0) package repository.
Searching the package via "pkg search make" provided the previously referenced version.

I did like this:
> ~/libbacktrace $ ./configure CC=clang CXX=clang++
> checking build system type... x86_64-unknown-freebsd13.0
> checking host system type... x86_64-unknown-freebsd13.0
> checking target system type... x86_64-unknown-freebsd13.0
> checking for gcc... clang
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether clang accepts -g... yes
> checking for clang option to accept ISO C89... none needed
> checking whether clang understands -c and -o together... yes
> checking how to run the C preprocessor... clang -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking minix/config.h usability... no
> checking minix/config.h presence... no
> checking for minix/config.h... no
> checking whether it is safe to define __EXTENSIONS__... yes
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> /home/oceanfish81/libbacktrace/missing: Unknown `--is-lightweight' option
> Try `/home/oceanfish81/libbacktrace/missing --help' for more information
> configure: WARNING: 'missing' script is too old or missing
> checking for a thread-safe mkdir -p... ./install-sh -c -d
> checking for gawk... no
> checking for mawk... no
> checking for nawk... nawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether to enable maintainer-specific portions of Makefiles... no
> checking for gcc... (cached) clang
> checking whether we are using the GNU C compiler... (cached) yes
> checking whether clang accepts -g... (cached) yes
> checking for clang option to accept ISO C89... (cached) none needed
> checking whether clang understands -c and -o together... (cached) yes
> checking for ranlib... ranlib
> checking for gawk... (cached) nawk
> checking for dwz... no
> checking how to print strings... printf
> checking for a sed that does not truncate output... /usr/bin/sed
> checking for fgrep... /usr/bin/grep -F
> checking for ld used by clang... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/local/bin/nm -B
> checking the name lister (/usr/local/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 393216
> checking whether the shell understands some XSI constructs... yes
> checking whether the shell understands "+="... no
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for ar... ar
> checking for strip... strip
> checking for ranlib... (cached) ranlib
> checking command to parse /usr/local/bin/nm -B output from clang object... ok
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if clang supports -fno-rtti -fno-exceptions... yes
> checking for clang option to produce PIC... -fPIC -DPIC
> checking if clang PIC flag -fPIC -DPIC works... yes
> checking if clang static flag -static works... yes
> checking if clang supports -c -o file.o... yes
> checking if clang supports -c -o file.o... (cached) yes
> checking whether the clang linker (/usr/bin/ld) supports shared libraries... yes
> checking dynamic linker characteristics... freebsd13.0 ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... no
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... no
> checking whether to build static libraries... yes
> checking for special C compiler options needed for large files... no
> checking for _FILE_OFFSET_BITS value needed for large files... no
> checking unwind.h usability... yes
> checking unwind.h presence... yes
> checking for unwind.h... yes
> checking for _Unwind_Backtrace... yes
> checking for -funwind-tables option... yes
> checking for -frandom-seed=string option... yes
> checking whether clang supports -W... yes
> checking whether clang supports -Wall... yes
> checking whether clang supports -Wwrite-strings... yes
> checking whether clang supports -Wstrict-prototypes... yes
> checking whether clang supports -Wmissing-prototypes... yes
> checking whether clang supports -Wold-style-definition... yes
> checking whether clang supports -Wmissing-format-attribute... yes
> checking whether clang supports -Wcast-qual... yes
> checking for _Unwind_GetIPInfo... yes
> checking __sync extensions... yes
> checking __atomic extensions... yes
> checking output filetype... elf64
> checking sys/mman.h usability... yes
> checking sys/mman.h presence... yes
> checking for sys/mman.h... yes
> checking for mmap... yes
> checking link.h usability... yes
> checking link.h presence... yes
> checking for link.h... yes
> checking for dl_iterate_phdr... yes
> checking mach-o/dyld.h usability... no
> checking mach-o/dyld.h presence... no
> checking for mach-o/dyld.h... no
> checking sys/ldr.h usability... no
> checking sys/ldr.h presence... no
> checking for sys/ldr.h... no
> checking for fcntl... yes
> checking whether strnlen is declared... yes
> checking whether getpagesize is declared... yes
> checking for lstat... yes
> checking for readlink... yes
> checking for getexecname... no
> checking for KERN_PROC... yes
> checking for KERN_PROG_ARGS... yes
> checking for clock_gettime... yes
> checking whether -pthread is supported... yes
> checking whether -gdwarf-5 is supported... yes
> checking for compress in -lz... yes
> checking whether --compress-debug-sections is supported... no
> checking for objcopy... objcopy
> checking for readelf... readelf
> checking whether objcopy supports debuglink... objcopy: stat failed: No such file or directory
> no
> checking for dsymutil... dsymutil
> checking for nm... /usr/local/bin/nm -B
> checking for xz... xz
> checking for comm... comm
> checking for lzma_auto_decoder in -llzma... yes
> checking whether tests can run... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating backtrace-supported.h
> config.status: creating install-debuginfo-for-buildid.sh
> config.status: creating config.h
> config.status: config.h is unchanged
> config.status: executing libtool commands
> config.status: executing default commands

> ~/libbacktrace $ make -j8
> --- config.h ---
> --- all ---
> make  all-am
> --- atomic.lo ---
> --- config.h ---
> --- atomic.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=atomic.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o atomic.lo atomic.c
> --- backtrace.lo ---
> --- dwarf.lo ---
> --- elf.lo ---
> --- fileline.lo ---
> --- mmap.lo ---
> --- mmapio.lo ---
> --- posix.lo ---
> --- backtrace.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=backtrace.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o backtrace.lo backtrace.c
> --- dwarf.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=dwarf.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o dwarf.lo dwarf.c
> --- elf.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=elf.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o elf.lo elf.c
> --- fileline.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=fileline.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o fileline.lo fileline.c
> --- atomic.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=atomic.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c atomic.c -o atomic.o
> --- mmap.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=mmap.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o mmap.lo mmap.c
> --- mmapio.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=mmapio.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o mmapio.lo mmapio.c
> --- posix.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=posix.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o posix.lo posix.c
> --- dwarf.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=dwarf.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c dwarf.c -o dwarf.o
> --- fileline.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=fileline.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c fileline.c -o fileline.o
> --- backtrace.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=backtrace.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c backtrace.c -o backtrace.o
> --- elf.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=elf.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c elf.c -o elf.o
> --- posix.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=posix.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c posix.c -o posix.o
> --- mmapio.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=mmapio.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c mmapio.c -o mmapio.o
> --- mmap.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=mmap.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c mmap.c -o mmap.o
> --- print.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=print.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o print.lo print.c
> --- simple.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=simple.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o simple.lo simple.c
> --- sort.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=sort.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o sort.lo sort.c
> --- state.lo ---
> --- print.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=print.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c print.c -o print.o
> --- state.lo ---
> /bin/sh ./libtool  --tag=CC    --mode=compile clang -DHAVE_CONFIG_H  -I.     -funwind-tables -frandom-seed=state.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2 -c -o state.lo state.c
> --- simple.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=simple.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c simple.c -o simple.o
> --- sort.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=sort.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c sort.c -o sort.o
> --- state.lo ---
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -funwind-tables -frandom-seed=state.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -g -O2 -c state.c -o state.o
> --- libbacktrace.la ---
> /bin/sh ./libtool  --tag=CC    --mode=link clang -funwind-tables -frandom-seed=libbacktrace.la -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual  -g -O2    -o libbacktrace.la -rpath /usr/local/lib atomic.lo dwarf.lo fileline.lo posix.lo  print.lo sort.lo state.lo backtrace.lo simple.lo  elf.lo  mmapio.lo  mmap.lo
> libtool: link: ar cru .libs/libbacktrace.a  atomic.o dwarf.o fileline.o posix.o print.o sort.o state.o backtrace.o simple.o elf.o mmapio.o mmap.o
> libtool: link: ranlib .libs/libbacktrace.a
> libtool: link: ( cd ".libs" && rm -f "libbacktrace.la" && ln -s "../libbacktrace.la" "libbacktrace.la" )

**Comment by ianlancetaylor** [comment]
If `make --version` doesn't print anything, then you aren't using GNU make.  Running the libbacktrace testsuite currently requires using GNU make.
