### ISSUE TITLE
How to create the libbacktrace.so from the available Makefile ?

### ISSUE THREAD

**Issue by kribakarans** [ianlancetaylor/libbacktrace#58]
Hi, I was experimenting one of my C program to print its backtrace on crash. For that I was landed here from the google search and I wish to use this libbacktrace library. I was compiled the code and seeing only the archive files and not seeing any .so file.
```
libtool: link: ranlib .libs/libbacktrace.a
libtool: link: ( cd ".libs" && rm -f "libbacktrace.la" && ln -s "../libbacktrace.la" "libbacktrace.la" )
```

In my tool, I want to use the libbacktrace as SO file. So, could you please guide me to generate the SO file to make my work complete.

I was refered the Makefile.am and searched the TARGET for SO creation but not found.

**Comment by ianlancetaylor** [comment]
When you run `configure`, pass the `--enable-shared` argument.
