### ISSUE TITLE
Consider provide a simple and standard way to output stack trace text

### ISSUE THREAD

**Issue by taozuhong** [ianlancetaylor/libbacktrace#66]
Consider provide a simple and standard way to output stack trace text
```
extern int backtrace_standard (struct backtrace_state *state, int skip, char** buffer, backtrace_error_callback error_callback, void *data);
```

**Comment by ianlancetaylor** [comment]
How would this be different from `backtrace_print`?

**Comment by taozuhong** [comment]
backtrace_print output stack trace to file,  but text buffer is more convenient:  save to file or print

**Comment by ianlancetaylor** [comment]
Well, you can do that using `backtrace_full` anyhow.  I don't think it comes up often enough to add it to the library.
