### ISSUE TITLE
libbacktrace SEGV with compressed debug sections (-gz)

### ISSUE THREAD

**Issue by J-Richter** [ianlancetaylor/libbacktrace#7]
Libbacktrace does not seem to understand compressed debug sections. 
Compressed debug sections are generated with the -gz flag.
Instead the program hits a SEGV while generating the backtrace. This seems to be another bug. 
But I don't know if libbacktrace should be able to deal with faulty debug info.

**Comment by ianlancetaylor** [comment]
Yeah, I've done the work in the version in the GCC tree., I just need to find the time to copy it over.

**Comment by ianlancetaylor** [comment]
Support for compressed debug sections has now been merged.
