### ISSUE TITLE
Configure fails with bash syntax error

### ISSUE THREAD

**Issue by theloni-monk** [ianlancetaylor/libbacktrace#75]
Running ```source configure``` in bash results in error ```bash: configure: line 29: syntax error near unexpected token `newline'                                                  'ash: configure: line 29: `     ;; ```
I installed libbacktrace as part of msys64 while trying to build the DAW application ZRythm

**Comment by ianlancetaylor** [comment]
Those lines are generated by autoconf.  Don't run `source configure`.  As with all autoconf-generated configure scripts, and pretty much all configure scripts in general, just run `configure` or `sh configure` or `bash configure`.  If you think it is important to support `source configure` for some reason, please file a bug against autoconf.

I'm not going to change anything in libbacktrace for this, so closing.
