### ISSUE TITLE
Split DWARF support

### ISSUE THREAD

**Issue by CallistoM** [ianlancetaylor/libbacktrace#76]
Does libbacktrace have any support for -gsplit-dwarf?

I don't know about the DWARF5 flavor, but with the GNU flavor there's a dwp tool that functions like dsymutil to generate a file.dwp containing the linked debug info from a -gsplit-dwarf build:
https://gcc.gnu.org/wiki/DebugFissionDWP

**Comment by ianlancetaylor** [comment]
libbacktrace supports debug info that is split out using objcopy and dwz, but it does not yet support `-gsplit-dwarf`.

**Comment by CallistoM** [comment]
Thanks for the information, decided to use LLVM's objcopy to split the debug information and use add-gnu-debuglink to the binary.
