### ISSUE TITLE
No backtrace info for x86_64 binary on AArch64 Windows 11

### ISSUE THREAD

**Issue by cme** [ianlancetaylor/libbacktrace#82]
I'm trying to get backtrace information for x86_64 executables on Windows, but the only Windows development environment I can really use to test this at the moment is Windows Insider Preview for AArch64 (running on an AArch64 Mac). It's an odd environment so there could be multiple reasons for this.

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/768466/147084805-c96e8ba5-911e-44a9-9f66-8b6d0d36649c.png">

Some initial digging shows that `libbacktrace` is getting the same symbol addresses visible in `objdump`, but at run-time the function addresses are at higher memory locations.

Address space layout randomisation? x86 emulation?

**Comment by cme** [comment]
Some further digging shows that the code at the higher addresses is indeed the same x86 code as the linked binary, at different page addresses, so it certainly *looks* like ASLR of some sort.

**Comment by BrettDong** [comment]
I tried adding `-Wl,--disable-dynamicbase -Wl,--disable-high-entropy-va` linker flags and then backtrace info returns normal:
![image](https://user-images.githubusercontent.com/21075502/147566894-613cf121-323f-40b7-a274-c4f2beee99e2.png)

So I guess it is ASLR.

**Comment by HazardyKnusperkeks** [comment]
I've created a patch series at https://gcc.gnu.org/pipermail/gcc-patches/2022-December/608031.html which solves this issue.

**Comment by ianlancetaylor** [comment]
The patch series was committed, so this should be fixed.
