### ISSUE TITLE
Outdated config.sub breaks compilation on macOS aarch64

### ISSUE THREAD

**Issue by Jarred-Sumner** [ianlancetaylor/libbacktrace#84]
To reproduce, run this on an M1:
```bash
git clone https://github.com/ianlancetaylor/libbacktrace
cd libbacktrace
./configure
```

The error it reports is:
```bash
checking build system type... Invalid configuration `arm64-apple-darwin21.2.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin21.2.0 failed
```

If you copy paste the latest `config.sub` from gcc, then `./configure` and `make` run successfully.

For reference, the config.sub I used was [from here](https://github.com/gcc-mirror/gcc/blob/master/config.sub)

**Comment by ianlancetaylor** [comment]
Thanks.  I updated the configury files.
