### ISSUE TITLE
ACX_PROG_CC_WARNING_OPTS syntax error near unexpected token `-W'

### ISSUE THREAD

**Issue by maikebing** [ianlancetaylor/libbacktrace#88]
```
./configure: line 12389: syntax error near unexpected token `-W'
./configure: line 12389: `ACX_PROG_CC_WARNING_OPTS(-W -Wall -Wwrite-strings -Wstrict-prototypes \'


```

gcc version 4.7.2 (Debian 4.7.2-5)
automake (GNU automake) 1.11.6

**Comment by ianlancetaylor** [comment]
Did you rerun autoconf?  If so, don't.  The generated files are in the repository already.  If you must rerun for some reason, be sure to use automake version 1.51.1, autoconf version 2.69, libtool version 2.2.7a.  And don't run them directly; run the existing configure script with `--enable-maintainer-mode` and then `make` will invoke them as needed.
