### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vlichevsky** [ianlancetaylor/libbacktrace#9]
After commit 17f687d2b9cb0b6e4441516947ac56784bc6264f only header files are installed by `make install`, but not the compiled library itself. Tested on Debian Sid, gcc version: 7.2.0, make version: 4.1

**Comment by thanm** [comment]
I'll take a look.

**Comment by ianlancetaylor** [comment]
Fixed.  Thanks for reporting it.
