### ISSUE TITLE
libbacktrace giving only relative path, even when absolute path is available in DWARF information

### ISSUE THREAD

**Issue by the-shank** [ianlancetaylor/libbacktrace#97]
Thanks for the wonderful library!

I am facing an issue wherein libbacktrace is providing only relative paths, despite absolute paths being available in the dwarf information:

For example, here is the relevant section from `llvm-dwarfdump` output for a particular binary that I built locally.
![image](https://user-images.githubusercontent.com/546476/203713466-a14c9316-0a1e-4ff6-a45d-00cb0aa08079.png)

And here is the backtrace produced using `backtrace_full`:
![image](https://user-images.githubusercontent.com/546476/203713730-f0e19714-88b6-4f7d-bfee-0858fbeb7787.png)

Is there a way to have libbacktrace provide absolute filenames?

**Comment by ianlancetaylor** [comment]
libbacktrace doesn't look at `DW_AT_decl_file`.  It gets the file name from the line header.  I'm not sure off-hand how to see that information using llvm-dwarfdump.  With readelf you can see it using `readelf --debug=line`.  Look for the "File Name Table".

**Comment by the-shank** [comment]
Thanks for the quick response:
This is the file name table I am gettting using `readelf --debug=line <binary>`
![image](https://user-images.githubusercontent.com/546476/203718231-41d9e2f3-a77a-416f-a95a-1f724a67bb83.png)

Does this in any way convey that the paths in the backtrace (using libbacktrace) would be relative?

**Comment by ianlancetaylor** [comment]
I would guess that you are executing something like `$CC src/core/fxfont.cpp` and that is probably where the directory entry is coming from.  You could try using an absolute path there.

In any case this doesn't seem like a bug in libbacktrace, so closing.
